void EnableOTA();
void readNRF();
void sendNRF(uint8_t fnID, uint16_t fndata);
void readCAN();
void sendCAN (uint8_t toID, uint8_t fnID, uint32_t fndata, uint32_t fndata2);
void WIFI_APSTART();
void konfiguracja();
void handle_NotFound();
void index_html();
void css_css();
void create_json();
void handleRoot();
void handleLogin();
void zmiana_poziomu_jasnosci();
void oneClick();
void DoubleClick();
void LongPressStart();
void LongPressStop();
void jasnoscLED();
void DimmWriteEEPROM();
void writeEEPROM(unsigned int adres, uint16_t dane, uint8_t dlugosc);
void SettingWriteEEPROM();
void FactoryWriteEEPROM();
void rysuj_jasnosc_na_lcd();
void rysujemy_na_lcd(void);
void aktualizuj_timestr();
void InicjacjaOdczytTemperatury();
void OdczytTemperatury();
void sprawdzSW1Touch();
void PokazSW1NaDisplay(boolean rundisplay);
uint8_t pobierzTouchVal(uint8_t TouchPin, uint8_t czymin, boolean isTouchPressed);
byte readEEPROM(unsigned int eeaddress );
void InicjacjaSW1Touch();
